### ISSUE TITLE
Install the system without ssl

### ISSUE THREAD

**Issue by mystyrious** [SecurityBrewery/catalyst#1057]
Following the installation guide - https://catalyst-soar.com/docs/catalyst/admin/install#installation-process
I tried to execute the installation with the --no-ssl flag:
bash install_catalyst.sh http://192.168.70.252 http://192.168.70.252 --no-ssl admin:admin:admin@example.com
But I got the error:
Error: hostname must start with https://
So I tried to install it with https in the hostname
As a result - I was able to access the ip only with http, https was not responding, but and all of the urls in the http page contained https links.
How can I install the system without certificate?

**Comment by cugu** [comment]
No `--no-ssl` flag is only for cases where you handle ssl termination at a load balancer or reverse proxy.
