### ISSUE TITLE
Could not connect to database

### ISSUE THREAD

**Issue by thomasboegl1** [SecurityBrewery/catalyst#1064]
Hi,

After trying to set get the docker stack up and running, I face the following error:

catalyst-1  | 2024/05/04 12:06:30 db.go:89: could not connect to database: not authorized to execute this request, retrying in 10 seconds

Everything else seems to be running correctly.

**Comment by cugu** [comment]
Did you run the setup script multiple times? I think arangodb might have mounted a volume created before and therefore use a different password, so that catalyst cannot connect.

**Comment by thomasboegl1** [comment]
Had possible artefacts that were comming from a previous installation. Cleaned everything and started again, working well as expected, thanks...

**Comment by cugu** [comment]
Glad to hear that, thanks for the feedback!
