### ISSUE TITLE
OpenAPI specification

### ISSUE THREAD

**Issue by cyberclansoc** [SecurityBrewery/catalyst#273]
Would like it if we had an OpenAPI specification JSON file for importing to other WebApps.

**Comment by theflyingjets** [comment]
I can work on this one.

**Comment by cugu** [comment]
Here you go: https://github.com/SecurityBrewery/catalyst/blob/main/generated/community.json

**Comment by theflyingjets** [comment]
No work needed, thank you!

**Comment by cugu** [comment]
@theflyingjets thanks for offering help though :)
