### ISSUE TITLE
Websocket connection issue

### ISSUE THREAD

**Issue by TechedJack** [SecurityBrewery/catalyst#429]
Hello,

I am currently trying to install Catalyst as per the secure install documentation for my organisation (public hospital)
I am now at the point where I have setup the new admin user in keycloak and changed the OIDC settings to match including secret and client ID etc.
When I browse the login page (catalyst.example.local/ui), enter the correct login details, and click login, the login button goes grey and disables and will not proceed any further.
After further investigation, I saw that the HTTP response header says "Wrong username or password" and in the catalyst container logs I can see the username and password are printed.

I also noticed in the network monitor on the browser that the websocket (/wss) is not able to be connected to, I have tried modifying the nginx.conf file to resolve this to no avail.
In the nginx logs, I see that the keep-alive connection for the websocket is getting disconnected - I'm unsure if this would cause this issue.

I will get some more detailed logs and screenshots when I am back at work on Monday, and I am working on this myself to hopefully see if I can make a PR to resolve this for others, but for now just posting this to see if anyone else has had this issue.

I am running this on Ubuntu Server 22.04 on vSphere

**Comment by CypherpunkSamurai** [comment]
Hello @TechedJack, would you mind uploading the nginx config you are currently using? Just in case, as this could also turn out to be a nginx config issue.

Thank You :)

**Comment by TechedJack** [comment]
Hi, @CypherpunkSamurai see below.
I've attached my nginx conf file as well as the error I get on the browser side and the logs seen on the server side.
Any help would be appreciated :)

[nginx.conf.txt](https://github.com/SecurityBrewery/catalyst/files/9473884/nginx.conf.txt)
![image](https://user-images.githubusercontent.com/67313633/188029381-6172f899-e272-4629-8c48-e6e19e84fdb4.png)
![image](https://user-images.githubusercontent.com/67313633/188029547-5b9ab95e-beea-4285-bdde-7aeef7cadaa9.png)

**Comment by CypherpunkSamurai** [comment]
The nginx config looks ok.

I would still suggest you try changing the nginx resolver and the proxy_send_timouts
```conf
location /wss {
      resolver        127.0.0.11 valid=60s;
      ...
      ...
      proxy_read_timeout 7d;
      proxy_send_timeout 7d;
   }
}
```

**Comment by TechedJack** [comment]
Hi,
I seem to still be getting the same issue as below
![image](https://user-images.githubusercontent.com/67313633/189576816-b99ecab2-cb14-46bc-8daa-afb37ec140a2.png)

![image](https://user-images.githubusercontent.com/67313633/189577124-74bb9fe5-8578-4439-a9f0-640ff1ee00bb.png)

![image](https://user-images.githubusercontent.com/67313633/189577157-992a2da0-70c6-4939-9031-7bf886cdfc9b.png)

As far as I can tell, there seems to be some issue with the websocket returning a redirect code?
I also tried to test the websocket with a chrome plugin, and it fails, but the logs show the below.
![image](https://user-images.githubusercontent.com/67313633/189576976-756d3704-3931-4493-a78d-0b44b8068b1e.png)

**Comment by cugu** [comment]
@TechedJack do you have the version of catalyst pinned in the `docker-compose.yml`. E.g. 

```
  …
  catalyst:
    image: ghcr.io/securitybrewery/catalyst:v0.9.2
    …
```

**Comment by TechedJack** [comment]
Hi @cugu I tried updating it to the latest release as well as using the pinned version – at the moment I’m using catalyst:main

***@***.***

From: Jonas Plum ***@***.***>
Date: Tuesday, 13 September 2022 at 9:14 pm
To: SecurityBrewery/catalyst ***@***.***>
Cc: JACK MOORE ***@***.***>, Mention ***@***.***>
Subject: Re: [SecurityBrewery/catalyst] Websocket connection issue (Issue #429)

@TechedJack<https://github.com/TechedJack> do you have the version of catalyst pinned in the docker-compose.yml. E.g.

  …



  catalyst:



    image: ghcr.io/securitybrewery/catalyst:v0.9.2



    …

**Comment by cugu** [comment]
Please use the pinned version. The main branch is not stable.
