### ISSUE TITLE
Conflict with arangobd on restart

### ISSUE THREAD

**Issue by trunishka** [SecurityBrewery/catalyst#673]
Every time when you restart docker with catalyst, it is trying to create "setup" key in arangodb without any checking if this key already exists, that causes an error 

`main.go:27: failed to create authenticator: HTTPError(409): unique constraint violated - in index primary of type primary over '_key'; conflicting key: setup`

Can there be any procedure that will check if "setup" exists in arango before trying to create it?

**Comment by jonas-plum** [comment]
As discussed on Discord, using version v0.10.1 will solve this.
