### ISSUE TITLE
Unable to login after installation

### ISSUE THREAD

**Issue by iZAK328** [SecurityBrewery/catalyst#675]
### 
- OS: POP OS

Hi, I had installed Catalyst on following the documentation but I had not provided any domain as parameter. 
![Command](https://user-images.githubusercontent.com/33455711/211364973-abea1b69-a690-46af-9ab8-33dbebc0f504.png)

However the installation had completed and I was able to see a login screen in which I entered the default admin creds and it threw me an error as shown below. 

![Login](https://user-images.githubusercontent.com/33455711/211364997-be13ae61-49b7-4107-8cf4-0a21459676e4.png)

Hoping that someone can help solve the issue. 

Thanks

**Comment by jonas-plum** [comment]
Which browser are you using? Are cookies activated?

**Comment by cugu** [comment]
So it is working fine in both browsers now?

There is a cookie set in the beginning. This might have failed due to browser settings or first startup.

**Comment by iZAK328** [comment]
Yes it seems to be working on Chrome. Thanks for your help!
