### ISSUE TITLE
Unable to login after installation 

### ISSUE THREAD

**Issue by iZAK328** [SecurityBrewery/catalyst#676]
# Login screen not showing 

| Server OS  | Client OS  | Client Browser |
| ---------- | ---------- | -------------
| Redhat 8.7 | Windows 10 | Chrome         |

Hi, 

I had an issue with the login screen not showing uo when after installing Catalyst on a machine in the cloud. 

The authentication URL had seemed to initially redirect to http://localhost:8082 which showed up on the browser address bar and didn't lead to any page.

So I had edited the `install_catalyst.sh` script with the following changes

```
    # set default domain
    if [ -z "$1" ]; then
        - echo "No domain provided, using default domain: localhost"
        + echo "No domain provided, using default domain: <IP>"
        - catalyst_domain="localhost"
        + catalyst_domain="<IP>"
    else
        catalyst_domain="$1"
    fi

    # set default hostname
    if [ -z "$2" ]; then
        - echo "No hostname provided, using default: http://localhost"
        + echo "No hostname provided, using default: http://<IP>"
        - catalyst_addr="http://localhost"
        + catalyst_addr="http://<IP>"
    else
        catalyst_addr="$2"
    fi

    # set default authelia hostname
    if [ -z "$3" ]; then
        - echo "No authelia hostname provided, using default: http://localhost:8082"
        + echo "No authelia hostname provided, using default: http://<IP>:8082"
        - authelia_addr="http://localhost:8082"
        + authelia_addr="http://<IP>:8082"
    else
        authelia_addr="$3"
    fi

```

After the above changes, on browsing to `http://<IP>`, I was greeted with the screen below
![image](https://user-images.githubusercontent.com/33455711/211970395-387ab800-99a2-44f8-8a2f-ea80a4f964ff.png)

On selecting *Login with OIDC* it redirected to `"http://<IP>:8082"` with a blank screen with no login prompt
![image](https://user-images.githubusercontent.com/33455711/211970495-01340950-54f7-454e-88c4-dd10b9a35db1.png)

Please let me know how to solve this issue. Thanks.

Please find the attached logs
[catalystlog1.txt](https://github.com/SecurityBrewery/catalyst/files/10397994/catalystlog1.txt)
[authelialog1.txt](https://github.com/SecurityBrewery/catalyst/files/10398013/authelialog1.txt)

**Comment by jonas-plum** [comment]
[Authelia (the authentication provider) only works over https](https://www.authelia.com/overview/prologue/architecture/#httphttps). So you need to set up domains and ssl first. I adapted the documentation and the setup script to clarify this and will provide better examples for installation soon.
