### ISSUE TITLE
Multiple sequential comments do not display correctly until the page is refreshed

### ISSUE THREAD

**Issue by graememeyer** [SecurityBrewery/catalyst#92]
If you add multiple comments in a row to an investigation ticket, the first comment is displayed multiple times instead of each new comment. When the page is refreshed, the comments then update to whatever you actually submitted.

Example before refresh:

![image](https://user-images.githubusercontent.com/3931530/163412900-e54e3707-3c8c-40de-bf1d-603388fca535.png)

After refresh:

![image](https://user-images.githubusercontent.com/3931530/163412957-50870cc8-23a2-4fcc-b62c-342e081ef6c8.png)

So far I'm really loving Catalyst!

**Comment by cugu** [comment]
Thank you for the kind words and the report :)

This should be fixed in v0.9.2
